{
  "hash": "5846459dce14ec009fd262f16633a922",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Five-Six -- Data Wrangling in R # Title of the document\n\n# Bibliography Details\nbibliography: Lab5References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab3WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Use the pipe operator (`|>`). It makes the data wrangling tasks much easier to write.\n* Use `head(...)` or `glimpse(...)` often to ensure your code did what you wanted it to and that you haven't accidentally deleted their entire dataset with a bad filter.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n\n**Timeline**\n\n* Week of 2/16: Aim to complete the data wrangling sections\n* Week of 2/23: Aim to complete the data summaries sections\n\n# Biomedical Science Data\n\n@Kitsberg25 collect data on the Human Cytomegalovirus (HCMV). HCMV is a member of the herpesvirus family -- the same family that includes: chickenpox, mononucleosis (mono), and cold sores. Prevalence is high with a worldwide seroprevalence of 24% to 100% [@Gupta25]. The virus persists in a dormant state for the entire life of those infected. Primary cytomegalovirus infection is often asymptomatic but can present with flu-like symptoms. The infection can reactivate due to stress, aging, or a weakened immune system.\n\nThe researchers obtained blood samples from healthy donors, males and females, aged 25-45. They infected the cells of primary (human donor's blood) or THP1 (purchased cell lines) monocytes ($n = 87$ and $n = 112$, respectively) and macrophages ($n = 93$ and $n = 170$, respectively) and counted the number of viral genomes in the nuclei.\n\nNote that the original donor of the THP-1 cell line was a 1-year-old Japanese boy. He was treated for Acute Monocytic Leukemia at Tohoku Hospital Pediatrics (THP-1; the first cell line there). Because they are malignant cancer cells, they can divide indefinitely, breaking the usual cell managment that usually reigns in rogue cells. Therefore, these cells can divide indefinitely in a lab environment. THP-1 cells, and those like them, serve as such a reliable, uniform model for medical research and improve reproducability.\n\n**Preliminary Question**: Are THP-1 cells a good stand-in for human cells?\n\n**Research Question**: Is the virus more prevalent in the nucleus of monocytes or macrophages, explaining why HCMV stays dormant in monocytes but goes active in macrophages?\n\n## Data Wrangling\n\n### Part A \nGo to the website and download the source data [https://www.nature.com/articles/s41467-025-68063-y#Sec30](https://www.nature.com/articles/s41467-025-68063-y#Sec30).\n\nDescribe the process -- do not leave out any steps -- for how you can load the data for Figures 3b and 3d from the manuscript into `R`. \n\n**Hint**: You can use packages like `readxl` [@readxl] but you will find it substantially easier to open the `.xls` file using your computer's spreadsheet software and create a new `.csv` file with the data you need.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg = read_csv(\"Fig 3B(Sheet1)-2.csv\")\ndat.kitsberg = dat.kitsberg[, -c(3, 4, 5, 6)]  # Getting rid of empty columns\n```\n:::\n\n\n \\normalsize\n\nI first went to the source data on the website. I downloaded the source data into Excel in an xls file and went to figure 3b. I then reorganized the data into two columns: sample and virus with nucleus to make it symmetric for a tibble, and then I downloaded the file as a csv to make it easier to use in R. I uploaded the csv in Positron to my lab 5-6 materials and then used read_csv to read the tibble using tidyverse.\n\n### Part B\nThe data need to be cleaned. Note that the sample type (Healthy Donor or THP-1), cell type (Monocytes or Macrophages), and treatment (12 Hours Post-Infection or Uninfected) are all recorded in one column `sample`, separated with underscores. Use `separate(...)` from the `tidyverse` package to separate the `sample` column into the `SampleType`, `CellType`, `Treatment` columns. Save the object as `dat.kitsberg.cleaned`.\n\n**Hint**: Use `?separate(...)` to see how it works.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dat.kitsberg |> \n  separate(col = sample, \n           into = c(\"SampleType\", \"CellType\", \"Treatment\"),\n           sep = \"_\",\n           remove = TRUE)\n```\n:::\n\n\n \\normalsize\n\n### Part C\nThe researchers are only interested in observations in the treatment group (12hpi). Remove uninfected samples from the data. Update `dat.kitsberg.cleaned` with the result.\n\n**Hint**: I would use the `filter(...)` function.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dat.kitsberg.cleaned |>\n  filter(Treatment == \"12hpi\")\n```\n:::\n\n\n \\normalsize\n\n### Part D\nWhen `CellType` is \"MDM\", it is a Monocyte-Derived Macrophages. That is, the cell type should be macrophages which is coded as \"mac\". Update `dat.kitsberg.cleaned` with the result.\n\n**Hint**: I would use the `mutate(...)` function. You will likely find `if_else(...)` or `case_when(...)` helpful.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dat.kitsberg.cleaned |>\n  mutate(\n    CellType = case_when(\n       CellType == \"MDM\" ~ \"mac\", \n       TRUE ~ CellType\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n## Part E\nThe researchers are only interested in monocytes and macrophages. Remove any other cell types. Update `dat.kitsberg.cleaned` with the result.\n\n**Hint**: I would use the `filter(...)` function.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dat.kitsberg.cleaned |>\n  filter(CellType %in% c(\"mac\", \"mono\"))\n```\n:::\n\n\n \\normalsize\n\n## Part F\nClean up the data entry. Replace the shorthand the researchers used with the neat sample type (Healthy Donor or THP-1), cell type (Monocytes or Macrophages), and treatment (12 Hours Post-Infection or Uninfected). Update `dat.kitsberg.cleaned` with the result.\n\n**Hint**: I would use the `mutate(...)` function. You will likely find `if_else(...)` or `case_when(...)` helpful.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dat.kitsberg.cleaned |>\n  mutate(\n    SampleType = case_when(\n      SampleType == \"primary\" ~ \"Healthy Donor\",\n      SampleType == \"THP1\" ~ \"THP-1\",\n      TRUE ~ SampleType\n    ),\n    CellType = case_when(\n      CellType == \"mac\" ~ \"Macrophages\",\n      CellType == \"mono\" ~ \"Monocytes\",\n      TRUE ~ CellType\n    ),\n    Treatment = case_when(\n      Treatment == \"12hpi\" ~ \"12 Hours Post-Infection\",\n      Treatment == \"uninfected\" ~ \"Uninfected\",\n      TRUE ~ Treatment\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n\n## Part G\nIn an `R` code block, combine your answers into one code block that completes the full cleaning process. Save the object as `dat.kitsberg.cleaned`.\n\n**Note**: You will use this in the next section\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dat.kitsberg |>\n  separate(col = sample, into = c(\"SampleType\", \"CellType\", \"Treatment\"), sep = \"_\") |> # Separate sample column into 3 columns\n  filter(Treatment == \"12hpi\") |> # Keep only infected samples\n  mutate(\n    CellType = case_when(\n       CellType == \"MDM\" ~ \"mac\", # Change MDM labels to \"mac\"\n       TRUE ~ CellType\n    ) \n  ) |>\n  filter(CellType %in% c(\"mac\", \"mono\")) |> # Keep only mac and mono cell types\n  mutate(\n    SampleType = case_when(\n      SampleType == \"primary\" ~ \"Healthy Donor\", #Renaming sample types\n      SampleType == \"THP1\" ~ \"THP-1\",\n      TRUE ~ SampleType\n    ),\n    CellType = case_when(\n      CellType == \"mac\" ~ \"Macrophages\", # Renaming cell types without abbreviations\n      CellType == \"mono\" ~ \"Monocytes\",\n      TRUE ~ CellType\n    ),\n    Treatment = case_when(\n      Treatment == \"12hpi\" ~ \"12 Hours Post-Infection\", # Renaming treatments without abbreviations\n      Treatment == \"uninfected\" ~ \"Uninfected\",\n      TRUE ~ Treatment\n    )\n  ) |>\n  rename(\n    VirusesWithinNucleus = `viruses within nucleus` # Rename column\n  )\n```\n:::\n\n\n \\normalsize\n\n## Data Summaries\n\n### Part A\nRecreate Figure 3b as depicted in the paper (see [https://www.nature.com/articles/s41467-025-68063-y#Fig3](https://www.nature.com/articles/s41467-025-68063-y#Fig3)). You can ignore the significance comparison because we haven't done that yet.\n\n**Hint**: I would use `geom_violin(...)` for Figure 3b I also expect your plots to look nicer -- better labels, better scaling, etc. Don't forget to use the proper formatting using the syntax in the Quarto cheatsheet.\n\n**Solution**\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(dat.kitsberg.cleaned) +\n  geom_violin(aes(x = CellType,\n    y = VirusesWithinNucleus, fill = CellType)\n    , alpha=0.5) +  \n  geom_boxplot(aes(x = CellType,\n                y = VirusesWithinNucleus, fill = CellType), # Fill by cell type to show both\n                width = 0.1)+\n    facet_wrap(~ SampleType) + # Facet by sample type, puts them side by side\n    theme_bw() +\n    labs(x = NULL,\n        y = \"HCMV Genomes in the Nucleus\",\n        fill = \"Cell Type\"\n  )\n```\n\n::: {.cell-output-display}\n![Viruses Within Nucleus Based on Cell Type](Lab5WriteUp_files/figure-pdf/fig-viruses-in-nucleus-1.pdf){#fig-viruses-in-nucleus fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n### Part B\nCompute a table containing relevant numerical summaries for Figure 3b.\n\n**Hint**: I would use `group_by(...)` and `summarize(...)` to complete this. Don't forget to use the proper formatting using `knitr::kable(...)` as described in the Quarto Cheatsheet.\n\n**Solution**\n\n \\normalsize\n\n\n::: {#tbl-nsum-viruses .cell tbl-cap='Viruses in the Nucleus Based on Cell Type' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|CellType    |SampleType    |Treatment               |   n| Mean|   SD| Median| IQR|\n|:-----------|:-------------|:-----------------------|---:|----:|----:|------:|---:|\n|Macrophages |Healthy Donor |12 Hours Post-Infection |  93| 0.37| 0.60|      0|   1|\n|Macrophages |THP-1         |12 Hours Post-Infection | 169| 0.33| 0.57|      0|   1|\n|Monocytes   |Healthy Donor |12 Hours Post-Infection |  87| 0.01| 0.11|      0|   0|\n|Monocytes   |THP-1         |12 Hours Post-Infection | 112| 0.04| 0.25|      0|   0|\n\n\n:::\n:::\n\n\n \\normalsize\n\nVirus counts in the nucleus vary across CellType and SampleType. And macrophages seem to have on average more viruses in the nucleus than monocytes (0.37 and 0.33 v.s. 0.01 and 0.04). Both have low counts of viruses overall. The variability within macrophages (SD and IQR) is also greater than for monocytes which indicates heterogeneous infection across cells, consistent with the broad distributions observed in the violin plots.\n\n# Ship Valuation\n\n![This is a ship-shipping ship shipping shipping ships.](meme.jpg){width=80%}\n\n@ElifBal25 aim to build a model for predicting the value of Supramax and Ultramax ships using both current and past market data. Their goal was to build a model that only uses information anyone can easily look up.\n\nThe researchers collected 17 years of real ship sale prices (2005–2022), covering $n=1819$ Supramax and Ultramax ship sales.\n\n**Research Question**: Can we predict Supramax and Ultramax ship prices?\n\n## Data Wrangling\n\n### Part A\nI downloaded the data from linked in the article ([https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0319073](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0319073)). I have included the data in this lab folder as `ShipValuation-Bal25.csv`. Load the data into `R`.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal = read_csv(\"ShipValuation-Bal25.csv\")\n```\n:::\n\n\n \\normalsize\n\n### Part B\nThe price of each Supramax and Ultramax ship is reported on the $\\log_{10}$ scale. Create a new column called `price` that contains the price in millions of dollars.\n$$\\text{Price} = \\frac{10^{\\text{SPLog}}}{1000000}$$\nSave the object as `dat.bal.cleaned`.\n\n**Hint**: I would use the `mutate(...)` function.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal |>\n  mutate(price = 10^SPLog/1000000)\n```\n:::\n\n\n \\normalsize\n\n### Part C\nThe authors recorded the country that each Supramax or Ultramax ship was built in in the columns `Japan`, `China, People's Republic Of`, `Philippines`, `Korea, South`,\t`Others Country Build`. These columns are marked `1` to indicate that is the country of origin and `0` otherwise. Create a new column called `OriginCountry` that contains a clean labels for the country in which the ship was built. Update `dat.bal.cleaned` with the result.\n\n**Hint**: I would use the `mutate(...)` function. You will likely find `if_else(...)` or `case_when(...)` helpful.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    OriginCountry = case_when( # Create new column\n       `Japan` == 1 ~ \"Japan\", # Change country names to be clearer, =1 to make sure you keep only ships where that is the country of origin\n       `China, People's Republic Of` == 1 ~ \"China\",\n       `Philippines` == 1 ~ \"Philippines\",\n       `Korea, South` == 1 ~ \"SouthKorea\",\n       `Others Country Build` == 1 ~ \"Other\",\n        TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n\n### Part D\nThe authors recorded each Supramax and Ultramax ship's main engine manufacturer in the columns `Caterpillar`, `MAN-B&W`, `Wartsila`, `Mitsubishi`. These columns are marked `1` to indicate that is the manufacturer and `0` otherwise. Create a new column called `Manufacturer` that contains a clean labels for the manufacturer. Update `dat.bal.cleaned` with the result.\n\n**Hint**: Follow the logic of the previous question.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    Manufacturer = case_when( # Make new column\n       `Caterpillar` == 1 ~ \"Caterpillar\", # =1 to keep only ships that have that manufacturer\n       `MAN-B&W` == 1 ~ \"MAN-B&W\",\n       `Wartsila` == 1 ~ \"Wartsila\",\n       `Mitsubishi` == 1 ~ \"Mitsubishi\",\n        TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n### Part E\nThe researchers recorded whether each Supramax and Ultramax ship is currently covered by a Protection and Indemnity (P\\&I) Club. This can be an indicator that a ship meets the minimum seaworthiness and safety requirements of the insurer.\n\nThe authors recorded P&I clubs in the columns `Japan P&I Club`, `Gard`,\t`West of England`,\t`North of England`, `UK P&I`, `Britannia P&I`, `London P&I Club`, `Skuld`, `Steamship Mutual`, `Others`, `Unknown`. These columns are marked `1` to indicate that the ship is insured by that P\\&I club and `0` otherwise. Create a new column called `PI.club` that contains a clean labels for the P\\&I club. Update `dat.bal.cleaned` with the result.\n\n**Hint**: Follow the logic of the previous questions.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    PI.club = case_when( # Make new column\n       `Japan P&I Club` == 1 ~ \"Japan P&I Club\", # =1 to make sure you keep only ships that are insured by each company \n       `Gard` == 1 ~ \"Gard\",\n       `West of England` == 1 ~ \"West of England\",\n        `North of England` == 1 ~ \"North of England\",\n        `UK P&I` == 1 ~ \"UK P&I\",\n        `Britannia P&I` == 1 ~ \"Britannia P&I\",\n        `London P&I Club` == 1 ~ \"London P&I Club\",\n        `Skuld` == 1 ~ \"Skuld\",\n        `Steamship Mutual` == 1 ~ \"Steamship Mutual\",\n        `Others` == 1 ~ \"Others\",\n        `Unknown` == 1 ~ \"Unknown\",\n        TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n### Part F\nThe researchers recorded whether each Supramax and Ultramax ship is classed by a society that requires a ship to be safe, structurally sound, and built/maintained to specific engineering standards.\n \nThe authors recorded class society in the columns `Nippon Kaiji Kyokai (IACS)`, `Lloyd's Register`, `Bureau Veritas (IACS)`, `Det Norske Veritas (IACS)`,\t`American Bureau of Shipping (IACS)`, `Others Class`, `With Two Classes`, `Disclassed`. These columns are marked `1` to indicate that the ship is classed by that soceity and `0` otherwise. Create a new column called `Class` that contains a clean labels for the class. Update `dat.bal.cleaned` with the result.\n\n**Hint**: Follow the logic of the previous questions.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    Class = case_when( # Create new column\n       `Nippon Kaiji Kyokai (IACS)` == 1 ~ \"Nippon Kaiji Kyokai (IACS)\", # =1 to keep only ships that are of that class\n       `Lloyd's Register` == 1 ~ \"Lloyd's Register\",\n       `Bureau Veritas (IACS)` == 1 ~ \"Bureau Veritas (IACS)\",\n        `Det Norske Veritas (IACS)` == 1 ~ \"Det Norske Veritas (IACS)\",\n        `American Bureau of Shipping (IACS)` == 1 ~ \"American Bureau of Shipping (IACS)\",\n        `Others Class` == 1 ~ \"Others Class\",\n        `With Two Classes` == 1 ~ \"With Two Classes\",\n        `Disclassed` == 1 ~ \"Disclassed\", \n        TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n### Part G\nThe researchers recorded the flag state of each Supramax and Ultramax ship. Each flag state enforces its own set of safety, environmental, and crew welfare rules and regulations. Ships under certain flag states may be more or less valuable depending on how much the flag affects the buyer's trust in the condition of the boat. \n \nThe authors recorded flag states in the columns `Panama`, `Marshall Islands`,\t`Liberia`,\t`Malta`,\t`Hong Kong`, `China`, `Singapore`, `Others Flag`, `With two flags`. These columns are marked `1` to indicate that the ship has that flag state and `0` otherwise. Create a new column called `FlagState` that contains a clean labels for the flag state. Update `dat.bal.cleaned` with the result.\n\n**Hint**: Follow the logic of the previous questions.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    FlagState = case_when(  # Create new column\n       Panama == 1 ~ \"Panama\", # =1 to keep only ships that have that flag state\n       `Marshall Islands` == 1 ~ \"Marshall Islands\",\n       Liberia == 1 ~ \"Liberia\",\n       Malta == 1 ~ \"Malta\",\n       `Hong Kong, China` == 1 ~ \"Hong Kong\",\n       `China, People's Republic Of` == 1 ~ \"China\",\n       Singapore == 1 ~ \"Singapore\",\n      `Others Flag` == 1 ~ \"Others Flag\", \n      `With two flags` == 1 ~ \"With two flags\",\n        TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n## Part H\nIn an `R` code block, combine your answers into one code block that completes the full cleaning process. Save the object as `dat.bal.cleaned`.\n\n**Note**: You will use this in the next section\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal = read_csv(\"ShipValuation-Bal25.csv\")\ndat.bal.cleaned = dat.bal |>\n  mutate(price = 10^SPLog/1000000) |>\n  mutate(\n    OriginCountry = case_when( # Create new column\n       `Japan` == 1 ~ \"Japan\", # Change country names to be clearer, =1 to make sure you keep only ships where that is the country of origin\n       `China, People's Republic Of` == 1 ~ \"China\",\n       `Philippines` == 1 ~ \"Philippines\",\n       `Korea, South` == 1 ~ \"SouthKorea\",\n       `Others Country Build` == 1 ~ \"Other\",\n        TRUE ~ NA_character_\n    )\n  ) |>\n  mutate(\n    Manufacturer = case_when( # Make new column\n       `Caterpillar` == 1 ~ \"Caterpillar\", # =1 to keep only ships that have that manufacturer\n       `MAN-B&W` == 1 ~ \"MAN-B&W\",\n       `Wartsila` == 1 ~ \"Wartsila\",\n       `Mitsubishi` == 1 ~ \"Mitsubishi\",\n        TRUE ~ NA_character_\n    )\n  ) |>\n    mutate(\n    PI.club = case_when( # Make new column\n       `Japan P&I Club` == 1 ~ \"Japan P&I Club\", # =1 to make sure you keep only ships that are insured by each company \n       `Gard` == 1 ~ \"Gard\",\n       `West of England` == 1 ~ \"West of England\",\n        `North of England` == 1 ~ \"North of England\",\n        `UK P&I` == 1 ~ \"UK P&I\",\n        `Britannia P&I` == 1 ~ \"Britannia P&I\",\n        `London P&I Club` == 1 ~ \"London P&I Club\",\n        `Skuld` == 1 ~ \"Skuld\",\n        `Steamship Mutual` == 1 ~ \"Steamship Mutual\",\n        `Others` == 1 ~ \"Others\",\n        `Unknown` == 1 ~ \"Unknown\",\n        TRUE ~ NA_character_\n    )\n  ) |>\n   mutate(\n    Class = case_when( # Create new column\n       `Nippon Kaiji Kyokai (IACS)` == 1 ~ \"Nippon Kaiji Kyokai (IACS)\", # =1 to keep only ships that are of that class\n       `Lloyd's Register` == 1 ~ \"Lloyd's Register\",\n       `Bureau Veritas (IACS)` == 1 ~ \"Bureau Veritas (IACS)\",\n        `Det Norske Veritas (IACS)` == 1 ~ \"Det Norske Veritas (IACS)\",\n        `American Bureau of Shipping (IACS)` == 1 ~ \"American Bureau of Shipping (IACS)\",\n        `Others Class` == 1 ~ \"Others Class\",\n        `With Two Classes` == 1 ~ \"With Two Classes\",\n        `Disclassed` == 1 ~ \"Disclassed\", \n        TRUE ~ NA_character_\n    )\n  ) |>\n  mutate(\n    FlagState = case_when(  # Create new column\n       Panama == 1 ~ \"Panama\", # =1 to keep only ships that have that flag state\n       `Marshall Islands` == 1 ~ \"Marshall Islands\",\n       Liberia == 1 ~ \"Liberia\",\n       Malta == 1 ~ \"Malta\",\n       `Hong Kong, China` == 1 ~ \"Hong Kong\",\n       `China, People's Republic Of` == 1 ~ \"China\",\n       Singapore == 1 ~ \"Singapore\",\n      `Others Flag` == 1 ~ \"Others Flag\", \n      `With two flags` == 1 ~ \"With two flags\",\n        TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n\n## Data Summaries\nFirst, I provide a short description of the other variables in their data. Note that the size ordering of types of ships discussed below is:\n\n$$\\text{Handysize} < \\text{Supramax} < \\text{Ultramax} < \\text{Panamax} < \\text{Capesize}$$\n\n* `DWT`: The deadweight tonnage, which is the maximum weight each Supramax and Ultramax ship can safely carry in metric tons. This gives a measure of how much cargo, fuel, fresh water, ballast water, provisions, and crew a ship can handle. \n* `Yas`: The age in years. New Supramax and Ultramax ships were recorded as having age 1.\n* `Enginges RPM`: Revolutions per minute of each Supramax and Ultramax ship's main propulsion engine. Generally speaking, lower-RPM engines are more expensive because they are more fuel efficient.\n* `BACI`: The Baltic Capesize Index. This describes freight rates for Capesize dry bulk ships, which reflects supply and demand. When BACI is high, Capesize ships are more profitable in shipping, which could positively affect Supramax and Ultramax ship values as demand for dry bulk commodities might be high and large shipments could be split into several Supramax and Ultramax shipments.\\\n**Note**: This reports the current BACI. The data also contain the BACI form 1, 2, and 3 months before the sale (`BACI-1`, `BACI-2`, `BACI-3`).\n* `BPNI`: The Baltic Panamax Index. This describes the cost to ship dry bulk commodities (e.g., coal or grain) on Panamax class ships. When BPNI is high, we expect Panamax ship prices to go up. Supramax and Ultramax ship values tend to follow this trend as charterers switch to these smaller vessels when Panamax rates become too expensive.\\\n**Note**: This reports the current BPNI. The data also contain the BPNI form 1, 2, and 3 months before the sale (`BPNI-1`, `BPNI-2`, `BPNI-3`).\n* `BSIS`: The Baltic Supramax Index. This describes freight rates for Supramax vessels, which reflects supply and demand. When BSIS is high, Supramax and Ultramax prices are usually higher because they are more profitable in shipping.\\\n**Note**: This reports the current BSIS. The data also contain the BSIS form 1, 2, and 3 months before the sale (`BSIS-1`, `BSIS-2`, `BSIS-3`).\n* `BHSI`: The Baltic Handysize Index. This describes freight rates for handysize vessels. When BHSI is high, Supramax and Ultramax ship prices are usually higher because the prices move together.\\\n**Note**: This reports the current BHSI. The data also contain the BHSI form 1, 2, and 3 months before the sale (`BHSI-1`, `BHSI-2`, `BHSI-3`).\n* `LIBOR`: The London InterBank Offered Rate. This describes the average reported interest rate at which banks would lend US dollars for 3 months.\n \n\n### Part A\nChoose a categorical variable. Create a plot and corresponding numerical summary to assess whether or how ship prices vary across the levels of the selected categorical variable.  \n\n**Solution**\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(dat.bal.cleaned) +\n  geom_boxplot(aes(x= Class, y = price),\n  width = 0.5)+\n    theme_bw() +\n    labs(x = \"Ship Class\",\n        y = \"Ship Price (millions of dollars)\"\n        ) +\n        coord_flip()\n```\n\n::: {.cell-output-display}\n![How Ship Prices Vary Across Classes](Lab5WriteUp_files/figure-pdf/fig-box-shipclasses-1.pdf){#fig-box-shipclasses fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {#tbl-fig-box-shipclasses .cell tbl-cap='How Ship Prices Vary Across Classes' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|Class                              |   n|  Mean|    SD| Median|   IQR|\n|:----------------------------------|---:|-----:|-----:|------:|-----:|\n|American Bureau of Shipping (IACS) | 170| 13.78|  8.61|  11.25| 10.97|\n|Bureau Veritas (IACS)              | 237| 18.53| 11.86|  16.00| 15.40|\n|Det Norske Veritas (IACS)          | 173| 17.55| 10.79|  15.25| 13.55|\n|Disclassed                         |   6|  7.73|  3.78|   7.10|  2.19|\n|Lloyd's Register                   | 269| 15.95| 11.03|  12.65| 12.70|\n|Nippon Kaiji Kyokai (IACS)         | 734| 17.31| 11.25|  14.87| 11.15|\n|Others Class                       | 203| 13.17| 10.71|  10.00|  8.87|\n|With Two Classes                   |  27| 17.89|  8.03|  16.70|  9.75|\n\n\n:::\n:::\n\n\n \\normalsize\n\nShip prices vary systematically across classes, however a lot of ship classes actually have similar mean prices between 15 and 18. Prices of disclassed and others class ships are much lower though (7.73 and 13.17 respectively). However, the distributions also show substantial within-class variation, indicated by relatively wide interquartile ranges and standard deviations. This suggests that while ship class is an important determinant of price, it is not the sole factor explaining variation in vessel value. Overall, the results indicate some relationship but not perfectly deterministic relationship between ship size class and market price.\n\n### Part B\nChoose a quantitative variable. Create a plot and corresponding numerical summary to assess whether or how ship prices vary with the selected quantitative variable.  \n\n**Solution**\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(dat.bal.cleaned) +\ngeom_point(aes(x = Yas,\n                 y = price)) +\n  geom_smooth(aes(x = Yas,\n                 y = price),\n              method = \"lm\",\n              color = \"black\") +\n  theme_bw() +\n  labs(x = \"Ship age (years)\",\n    y = \"Ship Price (millions of dollars)\"\n  )\n```\n\n::: {.cell-output-display}\n![How Ship Prices Vary with Ship Age](Lab5WriteUp_files/figure-pdf/fig-box-shipages-1.pdf){#fig-box-shipages fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {#tbl-fig-box-shipages .cell tbl-cap='How Ship Prices Vary with Ship Age' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|    n| correlation|\n|----:|-----------:|\n| 1819|       -0.51|\n\n\n:::\n:::\n\n\n \\normalsize\n\nThere is a negative relationship between ship age and price, meaning that older ships tend to be less valuable than newer ones. This is visible in the downward slope of the fitted linear regression line.\nThe Pearson correlation coefficient confirms this pattern (-0.51), indicating a moderate negative relationship between age and price. However, the relationship is not perfectly strong, indicating that other factors also play a substantial role in determining price. The scatter in the data shows considerable variation in prices at any given age, reinforcing this point.\n\n# Discussion\nThis lab required an extensive use of Tidyverse tools to clean two data sets. Initially we were given a messy data set in Excel (kitsberg data) that had to be manually edited to be symmetric and easier to use in R. Once this was converted into a csv file, we could use read_csv and store the data as an object (tibble) to keep using and clean. Functions like mutate(), filter(), and separate() were very important to reorganize and rename columns or other labels throughout the tibbles. Then, different figures such as violin plots, box plots, and scatter plots were used to most effectively plot qualitative and quantitative data. Sometimes tools such as facet_wrap were used to make the data easier to visualize and group things side by side. Lastly, summary() was used to create numerical summaries of the results from the plots, and I put these summaries into tables that are easy to interpret.\n\n# Citations\n[@readxl] is a useful tool for reading Excel files. I didn't use this however, as it was easier to convert the file to a csv first and use read_csv. [@Kitsberg25], [@Gupta25], and [@ElifBal25] gave us the data that we cleaned in parts 1 and 2 and were important resources throughout the lab.",
    "supporting": [
      "Lab5WriteUp_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}