{
  "hash": "1dcc0ccdfc29206d7b5d8a571c8d43c6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Tidyverse and ggplot2 Review: Reproducing Ecological Findings Using a Case Study of Hawksbill Turtle Nesting\" # Title of documnet\n\nexecute:\n  warning: false\n  message: false\n\nformat:\n  html: \n    number-sections: TRUE\n    code-fold: TRUE\n    code-line-numbers: TRUE\n    cap-location: top \n  pdf:\n    documentclass: article\n    number-sections: TRUE\n    code-line-numbers: TRUE\n    cap-location: top \n    include-in-header:\n      - text: |\n          \\usepackage{amsmath}\n          \\usepackage[dvipsnames]{xcolor}\n          \\usepackage[shortlabels]{enumitem}\n          \\usepackage{parskip}\n          \\usepackage{hyperref}\n          \\usepackage{geometry}\n          \\usepackage{float}\n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\nformat-links: [pdf]\n---\n\n## Why the Tidyverse Matters\n\nIn computational statistics, the **tidyverse** provides a consistent framework for working with data from cleaning to visualization. The tidyverse is a collection of R packages designed for data science that share a consistent structure and philosophy. Rather than treating data analysis as a series of disconnected steps, the tidyverse provides a unified workflow for importing, cleaning, transforming, and visualizing data.\n\nA central idea is that data analysis should be:\n\n* Readable (easy to interpret)\n* Reproducible (others can recreate your work)\n* Structured (data follows consistent rules)\n\nThe tidyverse is built around the concept of tidy data:\n\n* Each variable is a column\n* Each observation is a row\n* Each value is a single cell\n\nThis is important because maintaining this structure makes it much easier to apply functions and create visualizations. This matters because messy data (e.g. multiple variables in one column or inconsistent formatting) makes analysis harder and more error-prone. Converting data into tidy format is the most important preceding step in the workflow of data analyzation.\n\n### Data Manipulation with Dyplr\n\nThe package dplyr is used to manipulate and summarize data.\n\nKey functions within dplyr include: \n\n* filter()      # keep specific rows\n* select()      # keep specific columns\n* mutate()      # adds or changes columns\n* if_else()     # enables us to make two-level changes inside a mutate()\n* case_when()   # enables us to make two-or-more-level changes inside a mutate(0)\n* rename()      # rename columns\n* count()       # group by one or more variables and count the number of observations\n* group_by()    # define groups\n* summarize()   # compute summary statistics\n\nPipes:\n\n|> This symbol is called a pipe, and connects lines of code to each other while using the tidyverse. Rather than continuously updating a tibble (tidyverse version of a data frame) in individual steps, you can connect these acts together using pipes.\n\n### Data Reshaping with Tidyr\n\nThe package tidyr helps convert messy data into tidy format.\n\n* pivot_longer()  # wide: long format\n* pivot_wider()   # long: wide format\n\nThese functions are usesful for reshaping tibbles for readibility, and making them easier to perform other tidyverse tools on.\n\n## Why ggplot Matters\nThe package ggplot2 is used for creating visualizations based on the grammar of graphics.\nThis means plots are built in layers:\n\nCore components:\n\n* Data # the dataset you are drawing from\n* Aesthetics (aes)  # mappings (x, y, color, etc.)\n* Geoms # visual elements (points, bars, lines -> what kind of graph you want to make)\n* Labels: # titles and axis descriptions\n\n### Plotting: \n\n* coord_polar()   # doughnut plot\n* geom_col()/geom_bar() # bar charts\n\nThese are used for when you are plotting 1 Categorical variable. Grouped doughnut plots and bar charts can be used to plot 2 categorical variables.\n\n* geom_boxplot()  # boxplots\n* geom_violin()   # violin plots\n* geom_histogram() # histograms\n\nThese are used when plotting 1 Quantitative variable. Grouped boxplots, grouped violin plots, and grouped histograms can be used for plotting 1 Qualitative and 1 Quantitative variable.\n\n* geom_point()    # scatterplots\n* geom_smooth()   # regression lines\n\nThese are used for plotting 2 Quantitative variables\n\n### Other useful ggplot tools:\n\n**facet_wrap()**\nExample code:\n\n::: {.cell}\n\n```{.r .cell-code}\n# ggplot(turtles.clean, aes(x = `Curved Carapace Length`, y = clutch_size)) +\n#   geom_point() +\n#   facet_wrap(~region) +\n#   theme_bw()\n```\n:::\n\n\nWhy it's useful: shows whether relationships differ by region\n\n**fill aesthetic** \nExample code:\n\n::: {.cell}\n\n```{.r .cell-code}\n# ggplot(turtles.clean, aes(x = region, y = `Clutch Size`, fill = region)) +\n#   geom_boxplot() +\n#   theme_bw()\n```\n:::\n\n\nWhy it's useful: group comparison inside of plots, in this case boxplots would be colored by region\n\n### Numerical Summaries\n\n* table()\n* prop.table()\n\nUsed to create contingency tables for numerically summarizing 1 categorical or 2 categorical variables.\n\n* mean()\n* median()\n* sd()\n* iqr()\n* e1071::skewness()\n* e1071::kurtosis()\n\nUsed to numerically summarize 1 quantitative variable or 1 quantitative and 1 qualitative variable (grouped mean, median, sd...).\n\n* cor(..., method = )\n\nUsed to numerically summarize 2 quantitative variables, showing the correlation between them. Three different methods: \"pearson\", \"spearman\", \"kendall\".\n\n## Why These Tools Matter for This Project\n\nIn this analysis I will be doing, the **tidyverse** allows for:\n\n* Efficient cleaning of ecological data from a published study\n* Clear transformation and grouping of variables by region\n* Reproducible workflows using pipe (|>) syntax\n\nMeanwhile, **ggplot2** enables:\n\n* Recreation of published figures\n* Clear comparison across global regions\n* Visualization of relationships \n\nTogether, these tools make it possible to move from raw data to meaningful conclusions in an organized and interpretable fashion. Overall, the tidyverse and ggplot2 provide a powerful framework for turning complex, real-world datasets into clear and effective analyses, which is essential in both statistics and applied research.\n\n## The Dataset\n\nThe data comes from a study examining hawksbill turtle nesting patterns in the Arabian Gulf. Researchers were interested in whether turtles in this extreme environment differ in size and reproductive behavior compared to global populations.\n\nWe will focus on variables such as:\n- Curved Carapace Length (CCL)\n- Curved Carapace Width (CCW)\n- Clutch size (number of eggs)\n\nIn this article, I will demonstrate this workflow using real ecological data on hawksbill sea turtles, a critically endangered species, using published data from PLOS ONE. I recreate several published figures from the article and explore the relationship between turtle size and reproductive output. The goal is not just to analyze the data, but to show how tools like dplyr and ggplot2 can help us think statistically.\n\n\n### Loading and Inspecting the Data\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nturtles = read_csv(\"pone.0203257.s001.csv\") # read the data file\n```\n:::\n\n\nAfter loading the dataset, it is important to inspect its structure and identify potential issues. Real-world datasets are rarely perfectly formatted for analysis, and this dataset contains missing values and unclear column names that must be addressed before visualization or modeling.\n\n\n### Cleaning the Data\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nturtles.clean = turtles |>\n    select(-`Nesting Season Length (d)`, -`SCL`, -`CCW`, -`Reference`) |> # get rid of columns we are not using\n    drop_na(`CCL`, `Clutch Size`, `Region`) |> # drop missing values in useful columns\n    rename(`Curved Carapace Length` = CCL) # rename columns to be clearer\n```\n:::\n\n\nExplanation of Cleaning Steps:\n\n* Removing columns we are not using\n* Observations with missing values were removed to prevent errors in summary statistics and regression models. Since variables like CCL and clutch size are central to the analysis, incomplete rows would reduce accuracy.\n* Renaming variables (rename()): Column names were made more descriptive to improve readability and make plots easier to interpret.\n\nAfter cleaning, the dataset is better structured for analysis: each row represents a single observation, and each column represents a clearly defined variable. This aligns with tidy data principles and ensures an easier time later using visualization tools like ggplot2.\n\n## Recreating Figures using ggplot2\n\nHere are my recreations of their figures (2, 3, 5) using **ggplot2** tools for data visualizations and accompanied numerical summaries.\n\n### Figure 2 \n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nturtles.clean |>\n  ggplot(aes(x = Region, y = `Curved Carapace Length`)) +\n  geom_boxplot(width = 0.6) +\n  labs(\n    x = \"Region\",\n    y = \"CCL (cm)\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Comparison of Curved Carapace Length Across Regions](tidyverse-review_files/figure-html/fig-ccl-across-regions-1.png){#fig-ccl-across-regions fig-align='center' width=480}\n:::\n:::\n\n\n\n::: {#tbl-ccl-by-region .cell tbl-cap='Curved Carapace Lengths Across Regions' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|Region        | mean.ccl| median.ccl| sd.ccl| iqr.ccl| skew.ccl| e.kurt.ccl| n.ccl|\n|:-------------|--------:|----------:|------:|-------:|--------:|----------:|-----:|\n|Arabian Gulf  |    70.93|      71.00|   3.01|    4.00|    -0.04|       0.99|   181|\n|Caribbean     |   104.85|     105.30|   7.37|   10.93|     0.11|      -0.46|   124|\n|Indian Ocean  |    70.04|      72.30|   4.31|    6.30|    -0.68|      -1.47|     9|\n|Red Sea       |    69.17|      69.30|   5.37|    6.17|    -0.76|       0.04|    26|\n|West Atlantic |    97.92|      97.85|   6.34|    9.50|     0.16|      -0.79|    38|\n\n\n:::\n:::\n\n\nThe distribution of curved carapace length (CCL) varies noticeably across regions. Both the visualization and the summary statistics indicate that turtles in the Arabian Gulf tend to have a lower mean CCL (70.89) compared to other regions, while turtles in the Caribbean tend to have the largest mean CCL (104.85) compared to other regions. This supports the conclusion that hawksbill turtles in the Arabian Gulf are physically smaller than their global counterparts.\n\n### Figure 3\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nturtles.clean |>\n  ggplot(aes(x = Region, y = `Clutch Size`)) +\n  geom_boxplot(width = 0.6) +\n  labs(\n    x = \"Region\",\n    y = \"Clutch Size (number of eggs)\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Comparison of Clutch Size Across Regions](tidyverse-review_files/figure-html/fig-clutch-size-across-regions-1.png){#fig-clutch-size-across-regions fig-align='center' width=480}\n:::\n:::\n\n\n\n::: {#tbl-clutch-size-by-region .cell tbl-cap='Clutch Sizes Across Regions' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|Region        | mean.clutch| median.clutch| sd.clutch| iqr.clutch| skew.clutch| e.kurt.clutch|   n|\n|:-------------|-----------:|-------------:|---------:|----------:|-----------:|-------------:|---:|\n|Arabian Gulf  |       79.31|         80.00|     16.50|      20.00|        0.19|         -0.31| 181|\n|Caribbean     |      135.08|        131.30|     23.52|      34.65|        0.26|         -0.69| 124|\n|Indian Ocean  |       97.22|         93.00|     15.78|      28.00|       -0.02|         -1.80|   9|\n|Red Sea       |       99.83|         98.70|     26.55|      28.05|       -0.12|         -0.20|  26|\n|West Atlantic |      132.50|        127.85|     35.41|      49.55|        0.03|         -0.53|  38|\n\n\n:::\n:::\n\n\nClutch size also shows clear regional differences. The Arabian Gulf exhibits a lower mean clutch size (78.37), indicating reduced reproductive output relative to other populations. The relatively small spread (sd=16.55, iqr=20.00) in the data suggests that this is a consistent pattern rather than a result of a few unusually small clutches. Together, the numerical summaries and visualization reinforce the idea that turtles in this region produce fewer eggs, which may have important implications for population sustainability.\n\n### Figure 5\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nturtles.clean |>\n  ggplot(aes(x = `Curved Carapace Length`, y = `Clutch Size`)) +\n  geom_point(alpha = 0.6) +\n  geom_smooth(method = \"lm\") +\n  labs(\n    x = \"CCL (cm)\",\n    y = \"Clutch Size\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Relationship Between Turtle Size and Clutch Size](tidyverse-review_files/figure-html/fig-turtle-size-v-clutch-size-1.png){#fig-turtle-size-v-clutch-size fig-align='center' width=480}\n:::\n:::\n\n\n\n::: {#tbl-ccl-v-clutch-size .cell tbl-cap='Correlation of Curved Carapce Length and Clutch Size' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|   n| corr|\n|---:|----:|\n| 378| 0.74|\n\n\n:::\n:::\n\n\nThe scatterplot and regression line indicate a positive relationship between curved carapace length (CCL) and clutch size. This relationship is supported by the positive Pearson correlation coefficient (0.74), which quantifies the strength of the linear relationship between the two variables. Although the relationship is not perfectly strong, the trend suggests that larger turtles tend to produce more eggs on average. This aligns with the orignal study's expectations that body size is linked to reproductive capacity, and helps explain some of the regional differences observed in earlier figures (2, 3).\n\n## Statistical Methods Used\n\nTo formally compare differences across regions, the original study used Analysis of Variance (ANOVA). This method tests whether the means of a variable (such as CCL or clutch size) differ significantly across multiple groups. Rather than comparing regions pairwise, ANOVA evaluates all groups simultaneously to determine if at least one group mean is different.\n\nIn this analysis, the visual differences observed in Figures 2 and 3 (CCL and clutch size across regions) are consistent with what ANOVA is designed to detect: systematic differences in group means rather than random variation. However, these visualizations created with ggplot2 are much clearer and more effective than those made using ANOVA.\n\nThen, to examine the relationship between turtle size and reproductive output, linear regression was used. Linear regression models the relationship between an independent variable (CCL) and a response variable (clutch size), allowing us to estimate how changes in body size are associated with changes in reproductive output.\n\nThis relationship was further summarized using the Pearson correlation coefficient, which quantifies the strength and direction of the linear association between the two variables. The positive correlation observed supports the trend shown in the regression plot: larger turtles tend to produce more eggs.\n\nTogether, towards this study, these statistical methods complement the visualizations by providing a formal framework for interpreting differences between regions and relationships between variables.\n\n## Reflection\n\nThis project exemplifies how raw ecological data is transformed into meaningful statistical conclusions. The most important skills I used were structuring and interpreting real-world, messy data using tidyverse and visualizing the data after using ggplot2\n\nRather than thinking of plots as final outputs, I have learned, through this course, to use them as tools for exploring patterns in the data. In this case, plots were used to examine differences between regions and relationships between variables.\n\nMost importantly, I have learned that statistical analysis is more than computing numbers. Visualization and numerical summaries work together to support interpretations, and both are necessary for drawing clear and convincing conclusions from data.",
    "supporting": [
      "tidyverse-review_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}