{
  "hash": "f6a96f8c27fda22be1edc8ead43ccf87",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Eight -- Probability # Title of the document\n\n# Bibliography Details\nbibliography: Lab8References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab8WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n# The Binomial and Negative Binomial Distributions\n\n## The Binomial Distribution\nIn many introductory courses, we make the simplifying assumption of independence in Bernoulli trials. For example, when playing best two-out-of-three legs in a darts match, we would assume Player A has an 70% chance of winning each leg. We write:\n$$X \\sim \\text{Binomial}(n=3, p=0.70)$$\nwhere\n\n* $X$ is the number of legs won\n* $n$ is the number of trials \n* $p$ is the probability of the event of interest\n\nOf note, it is not necessarily the case that the players play all three legs -- if either player wins legs one and two the match ends.\n\nThere are eight possible outcomes for Player A:\n\n* (win, win, \"win\") $\\longrightarrow$ Player A wins\n* (win, win, \"lose\") $\\longrightarrow$ Player A wins\n* (win, lose, win) $\\longrightarrow$ Player A wins\n* (win, lose, lose) $\\longrightarrow$ Player A loses\n* (lose, win, win)  $\\longrightarrow$ Player A wins\n* (lose, win, lose) $\\longrightarrow$ Player A loses\n* (lose, lose, \"win\") $\\longrightarrow$ Player A loses\n* (lose, lose, \"lose\") $\\longrightarrow$ Player A loses\n\n**Note**: I use quotations above to denote outcomes where the last match isn't actually played.\n\n**Use the Binomial distribution to compute the probability that Player A wins the match.  Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nn = 3\np = 0.70 #define parameters\n\nggdat <- tibble(x = 0:3,\n                PMF = dbinom(x, n, p),\n                CDF = pbinom(x, n, p)) #plot PMF and CDF\nPMF.plot <- ggplot(ggdat) +\n  geom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x >= 2),\n                 aes(x = x, ymin = 0, ymax = PMF),\n                 color = \"darkorchid2\", linewidth = 1.5) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Number of Legs Won\", y = \"Probability\")\n\nCDF.plot <- ggplot(ggdat) +\n  geom_step(aes(x = x, y = CDF)) +\n  geom_point(aes(x = x, y = CDF)) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Number of Legs Won\", y = \"Cumulative Probability\") \n\nPMF.plot | CDF.plot #plot PMF and CDF side by side\n```\n\n::: {.cell-output-display}\n![The Binomial Distribution with n = 3, p = 0.70](Lab8WriteUp_files/figure-pdf/fig-binomial-1.pdf){#fig-binomial fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n**Probability**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pbinom(1, size = 3, prob = 0.7) #Probability that X>=2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n## The Negative Binomial Distribution\nIn intermediate courses, we learn the Negative Binomial distribution that we use to model the number of \"failures\" until the $r$th success. Note that this approach still makes the simplifying assumption of independence in Bernoulli trials.\n\n**Specify the two cases necessary to compute the probability. Fully explain these probability statements in the context of a best two-out-of-three match and the Negative Binomial distribution. Finally, compute the probability that Player A wins the match and show you get the same result as the Binomial approach. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nr = 2\np = 0.7 #define parameters\n\nggdat <- tibble(x = -0:3) |>\n  mutate(PMF = dnbinom(x, size=r, prob=p),\n         CDF = pnbinom(x, size=r, prob=p)) #compute PMF and CDF\nPMF.plot <- ggplot(ggdat) +\n  geom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x <= 1),\n                 aes(x = x, ymin = 0, ymax = PMF),\n                 color = \"darkorchid2\", linewidth = 1.5) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Losses Before Two Wins\", y = \"Probability\")\n\nCDF.plot <- ggplot(ggdat) +\n  geom_step(aes(x = x, y = CDF)) +\n  geom_point(aes(x = x, y = CDF), size = 1) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Losses Before Two Wins\", y = \"Cumulative Probability\") \nPMF.plot | CDF.plot #plot PMF and CDF side by side\n```\n\n::: {.cell-output-display}\n![The Negative Binomial Distribution with r = 2, p = 0.70](Lab8WriteUp_files/figure-pdf/fig-nbinomial-1.pdf){#fig-nbinomial fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n**Probability**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnbinom(1, size = 2, prob = 0.7) #Probability that X<=1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe probability using the Binomial and Negative Binomial Distributions is the same. The Binomial Distribution measures how many wins occur in a given number of trials (3 trials), and looks for outcomes where at least 2 wins occur (won the match). The Negative Binomial Distribution goes from the opposite direction, and measures the number of losses before the desired event occurs (a win). r is 2, because a win needs to occur in the first 2 trials.\n\n# The Beta Binomial Distribution\nOne approach to generalize this modeling is to use a Beta-Binomial distribution. This distribution arrises when we let $p$ be a random variable that follows a Beta distribution:\n\\begin{align*}\n  P &\\sim \\text{Beta}(\\alpha, \\beta)\\\\\n  X &\\sim \\text{Binomial}(n, P).\n\\end{align*}\nThis distribution is not part of base `R`, but is available using the `_bbinom` functions from the `extraDistr` package [@extraDistr].\n\nThe primary benefit is that the Beta-Binomial enables us to specify some uncertainty about the skill of Player A, as $p$ does not have to be fixed (e.g., $p=0.70$). Suppose the result of the best two-out-of-three match follows a Beta-Binomial distribution  where $\\alpha=7$ and $\\beta=3$.\n\n## The Beta Part\n1. **Plot the corresponding Beta distribution. Interpret the plot in the context of a best two-out-of-three match and the Binomial distribution.**\\\n**Hint**: The Beta distribution is available in base `R` via `_beta()`.\n\n**Solution**\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3 #define parameters\n\nggdat <- tibble(x = seq(0, 1, length.out = 1000)) |>\n  mutate(PDF = dbeta(x, shape1 = alpha, shape2 = beta), \n          CDF = pbeta(x, shape1 = alpha, shape2 = beta)) #compute PDF and CDF\n\nPDF.plot <- ggplot() +\n  geom_line(data = ggdat,\n                 aes(x = x, y = PDF)) +\n  geom_ribbon(data=ggdat |> filter(x >= 0.7), #p is around 0.7, beta distribution allows for uncertainty\n              aes(x = x, ymin = 0, ymax = PDF),\n                 color = \"darkorchid2\", alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Number of Wins\", y = \"Density\")\n\nCDF.plot <- ggplot() +\n  geom_line(data = ggdat,\n              aes(x = x, y = CDF)) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Number of Wins\", y = \"Cumulative Probability\")\nPDF.plot | CDF.plot #plot PDF and CDF side by side\n```\n\n::: {.cell-output-display}\n![The Beta Distribution with alpha = 7, beta = 3](Lab8WriteUp_files/figure-pdf/fig-beta-1.pdf){#fig-beta fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThe Beta distribution shows us how likely different win probabilities, p, are for Player A. Most of the density is near 0.7, reflecting our belief from the Binomial example. The Beta distribution is helpful because it allows for uncertainty and variation in p, and wider view of Player A's performance.\n\n1. How does the Beta incorporate uncertainty about the skill of Player A? **Compute the mean and variance of the distribution.**\\\n**Hint**: You will find the `integrate(...)` function helpful here. \n\\begin{align*}\n  E(P) &= \\mu_P = \\int_{0}^1 p f_P(p) dp\\\\\n  var(P) &= \\sigma^2_P = \\int_{0}^1 (p-\\mu_P)^2 f_P(p) dp\\\\\n\\end{align*}\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3 #define parameters\n\nf_P = function(p) dbeta(p, shape1 = alpha, shape2 = beta) #function for PDF to make calculating the mean and variance simpler\n\n(E_P = integrate(function(p) p * f_P(p), lower = 0, upper = 1)$value) #Mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7\n```\n\n\n:::\n\n```{.r .cell-code}\n(Var_P = integrate(function(p) (p - E_P)^2 * f_P(p), lower = 0, upper = 1)$value) #Variance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01909091\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the probability that Player A has a win probability of exactly 0.70?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\\\n**Hint:** Think carefully about the properties of continuous distributions here.\n\n**Solution**\nThe probability that Player A has a win probability of exactly 0.70 is 0. This is because the PDF does not calculate probability, and is 0 at any single point (property of continuous distributions).\n\n1. **What is the probability that Player A has a win probability of at least 0.50?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\n1 - pbeta(q=0.50, shape1 = alpha, shape2 = beta) #Probability of at least 0.50\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9101562\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the 90th percentile of Player A's win probability based on this Beta distribution? Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the percentile using `ggplot`.**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 7\nbeta = 3\nqbeta(0.9, shape1 = alpha, shape2 = beta) #Inverse CDF\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8705027\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n## The Beta-Binomial Part\n**Compute the probability that Player A wins the match. Compare your result to the Binomial and Negative Binomial results. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`**\n\n**Solution**\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nlibrary(extraDistr) #download then load library\nn = 3       \nalpha = 7    \nbeta = 3   #define parameters\n\nggdat <- tibble(\n  x = 0:n,\n  PMF = dbbinom(x, size = n, alpha = alpha, beta = beta),\n  CDF = pbbinom(x, size = n, alpha = alpha, beta = beta)) #calculate PMF and CDF\n\nPMF.plot = ggplot(ggdat) +\n  geom_linerange(aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x >= 2),\n                 aes(x = x, ymin = 0, ymax = PMF),\n                 color = \"darkorchid2\", linewidth = 1.5, alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Number of Legs Won\", y = \"Probability\")\n\nCDF.plot <- ggplot(ggdat) +\n  geom_step(aes(x = x, y = CDF)) +\n  geom_point(aes(x = x, y = CDF), size = 1) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Number of Legs Won\", y = \"Cumulative Probability\")\nPMF.plot | CDF.plot #plot PMF and CDF side by side\n```\n\n::: {.cell-output-display}\n![The Beta Binomial Distribution with alpha = 7, beta = 3](Lab8WriteUp_files/figure-pdf/fig-bbinomial-1.pdf){#fig-bbinomial fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n**Probability**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 3       \nalpha = 7    \nbeta = 3 #define parameters\n1 - pbbinom(1, size = n, alpha = alpha, beta = beta) #calculate probability player a wins using CDF\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7636364\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe result, $0.76$ is a bit smaller than the result using the Binomial and Negative Binomial distributions ($0.78$), but very similar. This is because the Beta-Binomial incorporates uncertainty in Player A’s ability.\n\n## The Why\nCheck the expected value and variance of each distribution.\n\nAnalytically, we have\n\\begin{align*}\n  E(X) &= np  &&var(X) = np(1-p) \\tag{Binomial Distribution}\\\\\n  E(X) &= n\\left(\\frac{\\alpha}{\\alpha+\\beta}\\right)  &&var(X) = \\frac{n \\alpha \\beta (\\alpha + \\beta + n)}{(\\alpha+\\beta)^2(\\alpha + \\beta + 1)} \\tag{Beta-Binomial Distribution}\n\\end{align*}\n\n**For each distribution, compute the mean number of legs won for player A.**\\\n**Hint**: You can perform the sum over the finite support set here. \n\\begin{align*}\n  E(X)   = \\mu_X    &= \\sum_{i=0}^3 i f_X(i)\\\\\n  var(X) = \\sigma_X &= \\sum_{i=0}^3 (i-\\mu_X) f_X(i)\n\\end{align*}\n\n# Altham's Multiplicative Binomial Distribution\nWhile the Beta-Binomial enables us to model cases where winning has a clustering effect (e.g., a \"hot hand\").\n\n## Probability Mass Function\nThe mass function for this distribution is below. While it used to be available in the `MBD` package for `R`, this package is no longer available.\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}$$ \n\n**Write a function in `R` called `daltbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbinom = function(x, n, p, theta){\n  i_vals = 0:n #create object i_vals to make more concise\n  c_vals = sum(choose(n, i_vals) * p^i_vals * (1 - p)^(n - i_vals) * theta^(i_vals * (n - i_vals)))\n  pmf = (choose(n, x) * p^x * (1 - p)^(n - x) * theta^(x * (n - x))) / c_vals\nreturn(pmf)\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggdat = tibble(\nx = 0:3,\npmf_theta_05 = daltbinom(x, n = 3, p = 0.7, theta = 0.5),\npmf_theta_1 = daltbinom(x, n = 3, p = 0.7, theta = 1),\npmf_theta_15 = daltbinom(x, n = 3, p = 0.7, theta = 1.5) #calculate the PMF at each value of theta\n)\n\nggdat_long = ggdat |>\n  pivot_longer(cols = starts_with(\"pmf\"),\n               names_to = \"theta\",\n               values_to = \"PMF\") #edit the tibble\n\nPMF.plot = ggplot(ggdat_long) + \n  geom_linerange(aes(x = x, ymin = 0, ymax = PMF, color = theta),\n                 linewidth = 1.5, alpha = 0.7) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Number of Games Won\",\n       y = \"Probability\",\n       color = \"Theta\")\n\nprint(PMF.plot) #plot the PMF with each value of theta as a different color\n```\n\n::: {.cell-output-display}\n![PMF of Altham's Multiplicative Binomial Distribution with p = 0.7](Lab8WriteUp_files/figure-pdf/fig-altbinom-1.pdf){#fig-altbinom fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nAs theta changes, certain outcomes become more or less likely in a best 2 out of 3 match. A theta under 1 (0.5), favors more extreme options, which is why you see more observations of 3 wins and a few of 1 wins. When theta is 1, the outcomes are more evenly distributed because each game is being interpreted individually and has the same probability of winning. When theta is 1.5, it favors more moderate outcomes, which is why these results are more concentrated in the middle (1-2).\n\n## Cumulative Distribution Function\n**Use your `daltbinom()` function to create a `paltbinom()` function for computing the CDF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$.**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaltbinom = function(x, n, p, theta){\n  k_vals = 0:n #create object k_vals to make more concise\n  pdf_vals = daltbinom(k_vals, n, p, theta)\n  cdf = cumsum(pdf_vals) #cdf calculation is based on the pdf\n  return(cdf[x+1]) #n doesn't start at 0\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggdat = tibble(\nx = 0:3,\ncdf_theta_05 = paltbinom(x, n = 3, p = 0.7, theta = 0.5),\ncdf_theta_1 = paltbinom(x, n = 3, p = 0.7, theta = 1),\ncdf_theta_15 = paltbinom(x, n = 3, p = 0.7, theta = 1.5) #calculate the CDF at each value of theta\n)\n\nggdat_long = ggdat |>\n  pivot_longer(cols = starts_with(\"cdf\"),\n               names_to = \"theta\",\n               values_to = \"CDF\") #edit the tibble\n\nCDF.plot = ggplot(ggdat_long) + \n  geom_step(aes(x = x, y = CDF, color = theta)) +\n  geom_point(aes(x = x, y = CDF), size = 1) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Number of Games Won\",\n       y = \"Probability\",\n       color = \"Theta\")\n\nprint(CDF.plot) #plot the CDF with each value of theta as a different color\n```\n\n::: {.cell-output-display}\n![CDF of Altham's Multiplicative Binomial Distribution with p = 0.7](Lab8WriteUp_files/figure-pdf/fig-altbinom2-1.pdf){#fig-altbinom2 fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## The Winning Probability\n**Compute the probability that Player A wins the match using Altham's Multiplicative Binomial Distribution. Compare your result to the Binomial and Negative Binomial results. Compare your results to the Beta-Binomial model, too. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(p_win_05 = 1 - paltbinom(1, n = 3, p = 0.7, theta = 0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8592417\n```\n\n\n:::\n\n```{.r .cell-code}\n(p_win_1  = 1 - paltbinom(1, n = 3, p = 0.7, theta = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n\n```{.r .cell-code}\n(p_win_15 = 1 - paltbinom(1, n = 3, p = 0.7, theta = 1.5)) #compute the probabilities of winning with each different value of theta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.746993\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe probability of Player A winning the match is the same as the Binomial and Negative Binomial results when theta = 1 (0.784), but the probability is higher when theta is 0.5 (= 0.859, is observable also in the graphs). The probability is lower when theta is 1.5 (=0.747, which is also observable in the graphs).\n\n# Altham's Multiplicative Beta-Binomial Distribution\nYou may have wondered -- \"Can we do the Beta thing with Altham's version of the Binomial Distribution?\" The answer is yes!\n\n## Probability Mass Function\nThe mass function for this distribution is below. \n$$f_X(x) = \\left[\\int_{0}^1 dp\n\\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right)\\right]I(x \\in \\{0, 1, ..., n\\})$$\n\n**Write a function in `R` called `daltbbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $\\alpha=7$ and $\\beta=3$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match.**\\\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbbinom = function(x, n, alpha, beta, theta){ #create function\npmf = sapply(x, function(xi) { #Apply the calculation to each possible outcome xi, returning a vector of PMF values\n  integrand = function(p) {\n    choose(n, xi) * (p^xi) * ((1-p)^(n-xi)) * (theta^(xi*(n-xi))) *\n      (p^(alpha-1) * (1-p)^(beta-1)) * gamma(alpha+beta)/(gamma(alpha)*gamma(beta))\n  }\n  integrate(integrand, lower=0, upper=1)$value\n})\n  pmf = pmf / sum(pmf)   #normalize the probabilities so they sum to 1\n  return(pmf)\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nlibrary(extraDistr)\nn = 3       \nalpha = 7    \nbeta = 3   #define parameters\n\nggdat <- tibble(\n  x = 0:n,  \n  pmf_theta_05 = daltbbinom(x, n, alpha = alpha, beta = beta, theta = 0.5),\n  pmf_theta_1 = daltbbinom(x, n, alpha = alpha, beta = beta, theta = 1),\n  pmf_theta_15 = daltbbinom(x, n, alpha = alpha, beta = beta, theta = 1.5) #calculate the PMF at each value of theta\n)\n\nggdat_long = ggdat |>\n  pivot_longer(cols = starts_with(\"pmf\"),\n               names_to = \"theta\",\n               values_to = \"PMF\") #edit the tibble\n\nPMF.plot = ggplot(ggdat_long) + \ngeom_linerange(aes(x = x, ymin = 0, ymax = PMF, color = theta),\n                 linewidth = 1.5, alpha = 0.7) +\n  geom_hline(yintercept = 0) +\n  theme_bw() +\n  labs(x = \"Number of Games Won\",\n       y = \"Probability\",\n       color = \"Theta\")\n\nprint(PMF.plot) #plot the PMF, each theta is a different color\n```\n\n::: {.cell-output-display}\n![PMF of Altham's Multiplicative Beta-Binomial Distribution with alpha = 7, beta = 3](Lab8WriteUp_files/figure-pdf/fig-daltbbinom-1.pdf){#fig-daltbbinom fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n**Hint**: You can use the `integrate()` in `R` to compute the integral. Note that this requires the function to be vectorized -- it should be unless you have added any block conditionals. \n\n# A Comparison\nCompute the probabilities for all outcomes for Player A.\n\n* Loses 0-2 (LL\"L\", LL\"W\")\n* Loses 1-2 (WLL, LWL)\n* Wins 2-0 (WW\"W\", WW\"L\")\n* Wins 2-1 (LWW, WLW)\n\n**Note**: You'll need to define these outcomes in terms of the random variable. \n\n**Create a bar plot (or column plot) using `ggplot` to show the probability of each outcome under the following conditions:**\n\n* **Binomial**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = 0:3\nn = 3\np = 0.7 #define parameters\n\n(binom_probs = dbinom(x, size = n, prob = p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.027 0.189 0.441 0.343\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n* **Negative Binomial**\\\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np = 0.7\nr = 2 #define parameters\n\n(nbinom_probs = c(\n  dnbinom(0, size = r, prob = 1 - p),  # Lose 0–2\n  dnbinom(1, size = r, prob = 1 - p),  # Lose 1–2\n  dnbinom(1, size = r, prob = p),      # Win 2–1\n  dnbinom(0, size = r, prob = p)       # Win 2–0\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.090 0.126 0.294 0.490\n```\n\n\n:::\n:::\n\n\n \\normalsize\n**Note**: You can compute the lose probabilities the same way as the win probabilities using success probability ($1-p$)\n\n* **Beta-Binomial**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = 0:3\nn = 3\nalpha = 7\nbeta = 3 #define parameters\n\nlibrary(extraDistr) #load library\n(bbinom_probs = dbbinom(x, size = n, alpha = alpha, beta = beta))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04545455 0.19090909 0.38181818 0.38181818\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n* **Althman Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = 0:3\nn = 3\np = 0.7 #define parameters\n\n(altham_05 = daltbinom(x, n, p, theta = 0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05118483 0.08957346 0.20900474 0.65023697\n```\n\n\n:::\n\n```{.r .cell-code}\n(altham_15 = daltbinom(x, n, p, theta = 1.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0151049 0.2379021 0.5551049 0.1918881\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n* **Althman Beta-Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = 0:3\nn = 3\np = 0.7\nalpha = 7\nbeta = 3 #define parameters\n\n(altbb_05 = daltbbinom(x, n, alpha, beta, theta = 0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07968127 0.08366534 0.16733068 0.66932271\n```\n\n\n:::\n\n```{.r .cell-code}\n(altbb_15 = daltbbinom(x, n, alpha, beta, theta = 1.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02649007 0.25033113 0.50066225 0.22251656\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n**Plotting**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ndf = tibble(\n  outcome = factor(x, labels = c(\"Lose 0-2\", \"Lose 1-2\", \"Win 2-1\", \"Win 2-0\")),\n  Binomial = binom_probs,\n  BetaBinomial = bbinom_probs,\n  Altham_0.5 = altham_05,\n  Altham_1.5 = altham_15,\n  AlthamBB_0.5 = altbb_05,\n  AlthamBB_1.5 = altbb_15\n) |>\n  pivot_longer(-outcome, names_to = \"model\", values_to = \"prob\") #create and edit tibble with probabilities\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(df, aes(x = outcome, y = prob, fill = model)) +\n  geom_col(position = \"dodge\") +\n  theme_bw() +\n  labs(x = \"Match Outcome\", y = \"Probability\")\n```\n\n::: {.cell-output-display}\n![Player A Best-of-Three Match Outcome Probabilities Across Models](Lab8WriteUp_files/figure-pdf/fig-playerAprobs-1.pdf){#fig-playerAprobs fig-align='center' fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n**Comment on the differences in the context of a best two-out-of-three match.**\n\n**Solution**\nThis part shows how every model produces slightly difference probabilities by design. First, the Binomial model assumes a fixed and constant skill level, producing a moderate distribution of match outcomes. This model is fairly static. Then, the Beta-Binomial incorporates uncertainty in Player A’s ability, giving more variation in outcomes. This leads to more extreme outcomes such as 2–0 wins and 0–2 losses (observed in column plot). Altham’s model is different from both the Binomial and Beta-Binomial models in that it incorporates dependence between games. In Altham’s model, the dependence parameter theta affects only the intermediate outcomes (2–1 and 1–2). When theta>1, these outcomes are amplified, increasing the probability of matches that go to three games. Contrastingly, when theta<1, the intermediate outcomes are downweighted, increasing the probability of sweeps (2–0 or 0–2). So, larger values of theta lead to more balanced matches, while smaller values lead to more skewed outcomes. The Altham Beta-Binomial combines both uncertainty (from the Beta-Binomial model) and dependence (from Altham's model), resulting in the greatest variability and realistic distribution. Here, theta=1.5 produces the most streak-driven outcomes. In the context of a best two-out-of-three match, this shows how variations in player skill and game-to-game dependence can alter match results.\n\n## Citations \nThe Beta-Binomial distribution was used and analyzed in this lab with the @extraDistr package, which provides additional probability distributions not available in base R. This is how I computed probabilities using dbbinom and pbbinom.",
    "supporting": [
      "Lab8WriteUp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}