{
  "hash": "35d9f0b9fdc9451a07a287966ea9105a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Ten -- Point Estimation # Title of the document\n\n# Bibliography Details\nbibliography: Lab10References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab10WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n\n# Lab 8 Notes\n\n##  Altham's Multiplicative Binomial Distribution\n\nThe PMF for Altham's Multiplicative Binomial Distribution is\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}.$$ \nJust so we start on the same page, I have included my `R` function for computing probability using this distribution.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbinom <- function(x, size, prob, theta){\n  normalizing.constant <- 0\n  for(j in 0:size){\n    normalizing.constant <- normalizing.constant + \n      choose(size, j) * prob^j * (1-prob)^(size-j) * theta^(j*(size-j))\n  }\n  # Probability Mass at x=x\n  (1/normalizing.constant) *\n    choose(size, x) * prob^x * (1-prob)^(size-x) * theta^(x*(size-x)) *\n      (x>=0)*(x<=size)\n}\n```\n:::\n\n\n \\normalsize\n\n# Altham's Multiplicative Beta Binomial Distribution\nThe PMF for Altham's Multiplicative Beta Binomial Distribution is\n$$f_X(x) = \\left[\\int_{0}^1 \\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right) dp\\right]I(x \\in \\{0, 1, ..., n\\})$$\n\nJust so we start on the same page, I have included my `R` function for computing probability using this distribution.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbbinom.single <- function(x, size, alpha, beta, theta){\n    integrand <- function(p) {\n    sapply(p, # integrate will pass in a vector, so we use sapply to apply the following\n           function(p_val){\n             # f(x|p) * f(p|alpha, beta)\n             daltbinom(x, size, p_val, theta) * dbeta(p_val, alpha, beta)\n           }\n    )\n  }\n  # Probability Mass at x=x\n  # integrate(integrand, lower = 0, upper = 1)$value * (x>=0)*(x<=size)\n  # I shrink the bounds below to avoid log(0)=-infinty\n  # I use try() to catch when there is an error and avoid crashing\n  res <- try(integrate(integrand, lower = 1e-7, upper = 1 - 1e-7)$value * \n                  (x>=0)*(x<=size), \n             silent = TRUE)\n  # If there is an error, return a near-zero probability\n  if(inherits(res, \"try-error\")) return(0.1^6)\n  \n  res\n}\n# Write a function that works on a vector\ndaltbbinom <- function(x, size, alpha, beta, theta){\n  sapply(X=x, FUN=daltbbinom.single, size=size, alpha=alpha, beta=beta, theta=theta)\n}\n```\n:::\n\n\n \\normalsize\n\n# Question 1\n\nIn Lab 8, we use Altham's Multiplicative Binomial Distribution. Your job was to interpret the impact of $\\theta$ in that equation. In this lab, we will model the number of legs won in a best of eleven (first to six) match. \n\nTo help us think about the interpretation, something that was challenging before, let's try something a little more manageable.\n\n## Part a\nSuppose a player has a 50\\% chance of winning a specific leg, that is let $p=0.50$. Let's look at the probability they win ($x=6$) legs in the match. Compute this probability over a sequence from $\\theta=0.5$ to $\\theta=1.5$ and plot it using a line where the $x$-axis is $\\theta$ and the $y$-axis is $P(X=6)$.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np = 0.50\nx=6\nn=11 #define parameters\n\nggdat = tibble(theta = seq(0.5, 1.5, by = 0.01)) |>\n  mutate(prob = daltbinom(x = x, size = n, prob = p, theta = theta)\n  )\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nggplot(ggdat, aes(x = theta, y = prob)) +\n  geom_line() +\n  labs(x = expression(theta),\n    y = \"P(X = 6)\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Probability of Winning 6 Legs in a Match as Theta Changes](Lab10WriteUp_files/figure-html/fig-prob6-1.png){#fig-prob6 fig-align='center' width=480}\n:::\n:::\n\n\n \\normalsize\n\n## Part b\nNow, plot Altham's Multiplicative Binomial Distribution under the same parameters with $\\theta=0.50$, $\\theta=1$, and $\\theta=1.5$. Use `ncol=1` in `facet_wrap()` to plot the PMFs in a single column for comparing.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\np = 0.50\nn=11 #define parameters\n\nggdat = tibble(\n  x = rep(0:n, times = 3),\n  theta = rep(c(0.5, 1.0, 1.5), each = n + 1)) |>\n  mutate(\n    PMF = daltbinom(x = x, size = n, prob = p, theta = theta) #define PMF\n  )\n```\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nPMF.plot = ggplot(ggdat, #plot PMF\n  aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange() +\n  geom_hline(yintercept = 0) +\n  facet_wrap(~ theta, ncol = 1) + #facet wrap theta\n  scale_x_continuous(\"x\", breaks = 0:n) +\n  ylab(\"Probability\") +\n  theme_bw() \n\nPMF.plot\n```\n\n::: {.cell-output-display}\n![Altham's Multiplicative Binomial PMF](Lab10WriteUp_files/figure-html/fig-althambinomialpmf-1.png){#fig-althambinomialpmf fig-align='center' width=480}\n:::\n:::\n\n\n \\normalsize\n\n## Part c\nWhat is your best assessment of what $\\theta$ is doing in this setting. Consider when a 6-0 blowout is most likely, and when a 5-6 nail-biter is most likely. Note here we should treat the match as a fixed $n=11$ as we did for $n=3$ in Lab 8.\\\n**Note:** In lab 8, we saw that small $\\theta$ meant wins came in bunches (clumped together), so there were more 2-0 wins in a best of three series.\n\n**Solution**\nTheta, again, makes win distributions more likely to cluster around extremes (0 or 11) when it is smaller (0.5), and makes win distributions more likely in the center (5-6) when it is larger. My assessment is that when theta is smaller, it is putting more emphasis on game-to-game results and skill, meaning that if a player has won several games in a row already they are more likely to win the next game. When theta is larger, games are more independent and the results are less reliant on each other.\n\n# Question 2\n\n## Part a\nAltham's Multiplicative Binomial Distribution does not typically simplify to the clean $E(X)=np$ seen in the Binomial distribution, unless $\\theta = 1$. Write out the expression that would need to be solved to find $E(X^k)$, and then write a function that computes it given the proposed parameter values $p$ (`prob`) and $\\theta$ (`theta`).\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE.altbinom.k = function(k, size, prob, theta){ #create function\n  x.vals = 0:size #vector of x values\n  sum((x.vals^k) * daltbinom(x.vals, size, prob, theta))\n}\n```\n:::\n\n\n \\normalsize\n\n## Part b\nDescribe how you can use your answer to part a to find Method of Moments estimates for the parameters $p$ and $\\theta$ for Altham's Multiplicative Binomial Distribution based on data.\n\n**Solution**\nYou can create a function with (par, data, size) and define the parameters p and theta as parameters 1 and 2. then you set m1 equal to the mean of the given data, m2 equal to the mean of the given data^2, and so on. Then, for E1 and E2, you set these equal to E.altbinom.k (the function from part a) with k = 1,2... Using what you wrote for m1, m2, ... and E1, E2, ... do c(E1-m1, E2-m2) which should result in (0, 0). Then use nleqslv, putting in fn, x, data, size to output the Method of Moments estimator based on the specific data. Method of Moments is an approximation, that gives back the maximum likelihood of observing a certain outcome.\n\n## Part c\nWrite a function that computes the log-likelihood for Altham's Multiplicative Binomial Distribution, given data (`x`) and proposed parameter values $p$ (`prob`) and $\\theta$ (`theta`).\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nll.altham = function(par, data, size, mle=FALSE){\n  p = ifelse(mle, 1/(1 + exp(-par[1])), par[1])   \n  theta = ifelse(mle, exp(par[2]), par[2]) # exp gives the exponential to ensure p and theta are positive     \n  \n  ll = sum(log(daltbinom(x = data, size = size, prob = p, theta = theta))) #compute log likelihood\n  \n  ifelse(mle, -ll, ll)  \n}\n```\n:::\n\n\n \\normalsize\n\n## Part d\nDescribe how you can use your answer to part c to find Maximum Likelihood estimates for the parameters $p$ and $\\theta$ for Altham's Multiplicative Binomial Distribution based on data.\n\n**Solution**\nWe can use the log-likelihood function from part c to find Maximum Likelihood Estimates for p and theta by finding the parameter values that maximize the likelihood of the observed data. This can be done later using optim() to search for the values of p and theta that make the observed outcomes most probable. To ensure valid parameters, we can transform p to stay between 0 and 1 and theta to stay positive during optimization (in the ifelse statment in part c), then transform back to report the MLEs. A good starting point for optimization is the Method of Moments estimate from Part b.\n\n# Lab 10\nPeter \"Snakebite\" Wright is a two-time Professional Darts Corporation World Champion (2020, 2022) and a former World No. 1. He is one of the sport's most decorated players, winning nearly 50 PDC titles including the World Matchplay, UK Open, and multiple European Championships. \n\nIn 2024, he made The Premier League -- a league involving the eight best players that runs every Thursday night from February to May. In this season, he won two of eighteen matches, securing only four points. The spread in legs won was -43, meaning he lost 43 more legs than he won. This performance was rather quite bad. He was soundly trounced in almost all his match ups. \n\n\nThe 2024 standings are below:\n\n| Rank | Player             |\n|:-----|:-------------------|\n| 1    |Luke Littler        |\n| 2    |Luke Humphries      |\n| 3    |Michael van Gerwen  |\n| 4    |Michael Smith       |\n| 5    |Nathan Aspinall     |\n| 6    |Rob Cross           |\n| 7    |Gerwyn Price        |\n| 8    |Peter Wright        |\n\n\n## Summarize the 2024 Data\n\nIn `pdc2024.csv`, I have provided the data for the 2024 Premier League season. There are a few data cleaning steps to consider.\n\n  * Remove any matches with no `Score` (e.g., a bye or walkover)\n  * Nights 1 through 16 are best of 11 (first to 6), but the playoffs are extended. For consistency, keep nights 1 through 16 only.\n  * Make two columns `WinnerLegs` and `LoserLegs` that keep track of the number of legs each player has won\n  \n  Summarize the data. What do the data tell us about the breakdown of the results?\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.pdc = read.csv(\"pdc2024.csv\")\n\nlibrary(dplyr)\nlibrary(tidyr)\n  dat.pdc.cleaned = dat.pdc |>\n    filter(!is.na(Score)) |>\n    filter(!Score %in% c(\"bye\", \"walkover\")) |>\n    filter(Night %in% 1:16) |>\n    separate(Score, into = c(\"WinnerLegs\", \"LoserLegs\")) |>\n    mutate(WinnerLegs = as.numeric(WinnerLegs), #make numeric\n            LoserLegs = as.numeric(LoserLegs)) |>\n    filter(!is.na(WinnerLegs), !is.na(LoserLegs))\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribution of Match Outcomes by Losing Legs](Lab10WriteUp_files/figure-html/fig-matchoutcomes-1.png){#fig-matchoutcomes fig-align='center' width=672}\n:::\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {#tbl-summaryofpremierleaguescores .cell tbl-cap='Distribution of Match Outcomes' tbl-align='center'}\n::: {.cell-output-display}\n\n\n| LoserLegs| count|  prop|\n|---------:|-----:|-----:|\n|         1|     6| 0.054|\n|         2|    16| 0.144|\n|         3|    30| 0.270|\n|         4|    28| 0.252|\n|         5|    31| 0.279|\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {#tbl-summary .cell tbl-cap='Summary of Premier League Scores' tbl-align='center'}\n::: {.cell-output-display}\n\n\n| mean_loser| sd_loser| median_loser| iqr_loser| skew_loser| kurt_loser|\n|----------:|--------:|------------:|---------:|----------:|----------:|\n|      3.559|    1.196|            4|         2|     -0.374|     -0.846|\n\n\n:::\n:::\n\n\n \\normalsize\n\nFirst I cleaned the data by removing matches without valid scores, taking out byes and walkovers, and restricting the dataset to Nights 1 through 16. The score variable was then separated into WinnerLegs and LoserLegs, which were converted to numeric values. Table 2 summarizes the distribution of match outcomes by the number of legs won by the losing player. The table shows both the frequency and proportion of matches for each possible value of LoserLegs. Table 3 then shows the mean, sd, median, iqr of the scores. The results indicate that matches are generally competitive, with a higher concentration of outcomes where the losing player wins several legs (4 or 5). In contrast, matches where the losing player wins very few legs (0 or 1) occur less frequently, meaning complete blowouts are relatively uncommon. Overall, the mean number of losing legs is approximately 3.559, with a standard deviation of 1.196. The median is 4, and the interquartile range is 2, further indicating that most matches are fairly close.\n\n## Altham's Multiplicative Binomial Distribution\nFor each player in the 2024 season, use the number of legs won in each match to compute maximium likelihood estimates for $p$ and $\\theta$. \\\n**Note**: The \"for each\" here can be done more efficiently with a function or a loop!\n\n* Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner's legs and sometimes from the loser's legs.\n* Find the MLE for the player using this data. Ensure to report $p$ and $\\theta$ for each player in a nicely formatted table.\\\n**Note:** In Lecture on Monday, we used transformations to restrict how `optim()` searches the parameter space. For example, here, you might consider\n`p <- 1/(1+exp(-par[1]))` and `theta <- exp(par[2])`.\n* Make comments about the MLEs in the context of the standings.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nwinners = dat.pdc.cleaned |> \n  select(Player = Winner, LegsWon = WinnerLegs) \n\nlosers = dat.pdc.cleaned |>\n  select(Player = Loser, LegsWon = LoserLegs) \n\nplayer.data = bind_rows(winners, losers) #combine winner and loser rows\n\nll.altham = function(par, x, n = 11) {\n  p = 1 / (1 + exp(-par[1]))   \n  theta = exp(par[2])          # transform parameters\n\n  ll = sum(log(daltbinom(x, size = n, prob = p, theta = theta)))\n  \n  return(-ll)  # negative for minimization\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.altham.player = function(df) {\n  x = df$LegsWon\n  \n  #find MLE\n  fit = optim(\n    par = c(0, 0),\n    fn = ll.altham,\n    x = x\n  )\n  \n  tibble(\n    p.hat = 1 / (1 + exp(-fit$par[1])),\n    theta.hat = exp(fit$par[2])\n  )\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {#tbl-altham-mle .cell tbl-cap='Maximum Likelihood Estimates for Altham’s Model by Player' tbl-align='center'}\n\n|Player             | p.hat| theta.hat|\n|:------------------|-----:|---------:|\n|Gerwyn Price       | 0.383|     1.020|\n|Luke Humphries     | 0.461|     1.205|\n|Luke Littler       | 0.469|     1.316|\n|Michael Smith      | 0.426|     1.047|\n|Michael van Gerwen | 0.431|     1.023|\n|Nathan Aspinall    | 0.403|     1.186|\n|Peter Wright       | 0.317|     0.989|\n|Rob Cross          | 0.395|     1.014|\n:::\n\n\n \\normalsize\n\nThe estimated values of p and theta vary across players, showing differences in both performance and match dynamics. p represents the probability of winning an individual leg, so players with higher values of p.hat tend to win a greater proportion of legs. The parameter theta adds dependence between legs. Values of theta < 1 make outcomes cluster more, leading to streaks and more extreme match outcomes. In contrast, theta > 1 produces more alternation between players, resulting in more balanced matches. Comparing these results to the empirical distribution of match outcomes, the presence of many close matches (e.g., 6–5) is consistent with models that allow for dependence between legs. Players with higher theta values tend to show less clustered performance, while those with theta closer to 1 behave more like the independent Binomial model. Overall, these results provide evidence that Altham’s model offers a more flexible and accurate model for showing the dynamics of match play.\n\n## Altham's Multiplicative Beta Binomial Distribution\n\nFor each player in the 2024 season, use the number of legs won in each match to compute maxmium likelihood estimates for $p$ and $\\theta$.\\\n**Note**: The \"for each\" here can be done more efficiently with a function or a loop!\n\n* Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner's legs and sometimes from the loser's legs.\n* Find the MLEs for the player using this data. Ensure to report $\\alpha$, $\\beta$, and $\\theta$ for each player in a nicely formatted table.\\\n**Note 1**: Due to the computational complexity of `integrate()`, you should compute the logged probability for `0:6` once and add them according to the data in each player's vector.\n**Note 2**: In Lecture on Monday, we used transformations to restrict how `optim()` searches the parameter space.\n* Plot the underlying Beta($\\alpha$, $\\beta$) distribution for each player. \\\n**Note**: Add the mean and variance of the Beta to the table of MLEs. Recall\n\\begin{align*}\n E(X)   &= \\frac{\\alpha}{\\alpha+\\beta}\\\\\n sd(X) &= \\sqrt{\\frac{\\alpha\\beta}{(\\alpha+\\beta)^2(\\alpha+\\beta+1)}}\n\\end{align*}\n* Make comments about the MLEs in the context of the standings.\\\n**Note**: The players alternate who throws first in a leg has the mathematical \"head start\" to reach a finish before their opponent can take another turn. Players alternate who throws first with each leg.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nll.altham.bb = function(par, x, n = 11) {\n\n  alpha = exp(par[1])\n  beta  = exp(par[2])\n  theta = exp(par[3]) #transform parameters\n  \n  k.vals = 0:6\n  probs = sapply(k.vals, function(k) { #probabilities for each k\n    daltbbinom(k, size = n, alpha = alpha, beta = beta, theta = theta)\n  })\n  \n  ll = sum(log(probs[x + 1]))  # match probabilities to observed data\n  \n  return(-ll) # negative for minimization\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.altham.bb.player = function(df) {\n  x = df$LegsWon\n  \n  #Compute MLE\n  fit = optim(\n    par = c(0, 0, 0),\n    fn = ll.altham.bb,\n    x = x\n  )\n  \n  alpha = exp(fit$par[1])\n  beta  = exp(fit$par[2])\n  theta = exp(fit$par[3]) \n  \n  tibble(\n    alpha.hat = alpha,\n    beta.hat  = beta,\n    theta.hat = theta,\n    mean = alpha / (alpha + beta),\n    sd = sqrt(alpha * beta / ((alpha + beta)^2 * (alpha + beta + 1)))\n  )\n}\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {#tbl-althambb .cell tbl-cap='MLEs for Altham Beta-Binomial Model by Player'}\n\n|Player             | alpha.hat| beta.hat| theta.hat|  mean|    sd|\n|:------------------|---------:|--------:|---------:|-----:|-----:|\n|Gerwyn Price       |     0.264|    0.917|     3.175| 0.224| 0.282|\n|Luke Humphries     |     0.331|    0.490|     6.391| 0.403| 0.363|\n|Luke Littler       |     0.283|    0.384|    10.797| 0.425| 0.383|\n|Michael Smith      |     0.534|    1.068|     2.245| 0.334| 0.292|\n|Michael van Gerwen |     0.219|    0.454|     5.001| 0.325| 0.362|\n|Nathan Aspinall    |     2.468|    4.338|     1.492| 0.363| 0.172|\n|Peter Wright       |     1.786|    7.289|     1.214| 0.197| 0.125|\n|Rob Cross          |     0.268|    0.813|     3.202| 0.248| 0.299|\n:::\n\n\n \\normalsize\n\n\n \\scriptsize\n\n\n::: {.cell layout-align=\"center\" scale='80%'}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\n\nx.vals = seq(0, 1, length.out = 100)\n\n# Expand the data frame so each player has a row for each x\nplayer.density <- player.results.bb |>\n  select(Player, alpha.hat, beta.hat) |>\n  crossing(x.val = x.vals) |>\n  rowwise() |>\n  mutate(density = dbeta(x.val, alpha.hat, beta.hat)) |>\n  ungroup()\n\nggplot(player.density, aes(x = x.val, y = density)) +\n  geom_line(color = \"darkorchid\") +    \n  facet_wrap(~ Player) +  \n  labs(\n    x = \"Probability of Winning a Leg\",\n    y = \"Density\",\n  ) +\n  theme_bw() \n```\n\n::: {.cell-output-display}\n![Estimated Beta Distributions by Player](Lab10WriteUp_files/figure-html/fig-betabyplayer-1.png){#fig-betabyplayer fig-align='center' width=480}\n:::\n:::\n\n\n \\normalsize\n\nThe estimates of alpha, beta, and theta account for variation in player performance by allowing the probability of winning a leg to vary across matches. The mean of the Beta distribution represents the average probability of winning a leg, while the standard deviation captures variability in performance. Players with higher mean values tend to perform better overall. However, the nonzero variance indicates that performance is not constant, and may fluctuate across matches/opponents. This highlights a significant limitation of the standard Binomial model, which assumes a fixed probability of success across matches. The parameter theta continues to capture dependence between legs. As in the multiplicative binomial model, values of theta < 1 indicate clustering of outcomes, while values near 1 suggest approximate independence (same as previous observation). Compared to the simpler models, the multiplicative Beta-Binomial provides the best fit for the observed data by accounting for both differences in player ability and dependence between legs. This is particularly important for something like darts matches, where players alternate who throws first, creating potential advantages across legs and matches.\n\n## Executive Summary\nSummarize the work you've done here to provide a brief (200-300 word) data-driven summary of the 2024 Premier League season using your work in Lab 10. Your summary should be professional, clear, and all claims should be corroborated with statistical support.\n\n**Solution**\nThe 2024 Premier League Darts season exhibits a strong overall level of competitiveness, with most matches decided by relatively small margins. After cleaning the dataset to include only standard-format matches (Nights 1–16), the distribution of outcomes shows that losing players most frequently won 4 or 5 legs, while extreme outcomes such as 6–0 or 6–1 were rare. The mean number of losing legs was approximately 3.56 with moderate variability (SD around 1.20), indicating that matches were typically competitive.\n\nTo more deeply understand player performance and match dynamics, Altham’s multiplicative Binomial model was used to estimate each player’s probability of winning a leg (p) and the dependence parameter theta. Higher estimated values of p aligned closely with stronger players standings, confirming that leg-level success translates directly to overall match performance. The theta parameter created additional dependence between legs: values less than 1 indicated clustering (streaks of consecutive legs), while values greater than 1 suggested alternating outcomes. This highlights that match play is not purely independent from leg to leg.\n\nExtending the model further to the multiplicative Beta-Binomial distribution allowed the probability of winning a leg to vary across matches. This added flexibility makes it possible to capture both differences in player ability and variability in performance across legs. Players with higher estimated means in the Beta distribution performed better overall, while nonzero variance indicated fluctuations in form across matches.\n\nOverall, the analysis shows that the Beta-Binomial model provides the most realistic representation of match dynamics by incorporating both leg-to-leg dependence and variability in player performance, offering the most accurate statistical description of the 2024 season.",
    "supporting": [
      "Lab10WriteUp_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}